### ISSUE TITLE
No module named 'ftfy'

### ISSUE THREAD

**Issue by yeldarby** [roboflow-ai/zero-shot-object-tracking#1]
Looks like it might be missing from the requirements. This is from a fresh venv with `pip install -r requirements.txt` and Python 3.9:

```
(env) yeldarb@iUSB-C-You zero-shot-object-tracking % python clip_object_tracker.py --source ~/Downloads/cards-720.mov --url https://detect.roboflow.com/playing-cards-ow27d/1 --api_key {{SNIPPED}} 
Traceback (most recent call last):
  File "/Users/yeldarb/Code/zero-shot-object-tracking/clip_object_tracker.py", line 5, in <module>
    import clip
  File "/Users/yeldarb/Code/zero-shot-object-tracking/clip/__init__.py", line 1, in <module>
    from .clip import *
  File "/Users/yeldarb/Code/zero-shot-object-tracking/clip/clip.py", line 13, in <module>
    from .simple_tokenizer import SimpleTokenizer as _Tokenizer
  File "/Users/yeldarb/Code/zero-shot-object-tracking/clip/simple_tokenizer.py", line 6, in <module>
    import ftfy
ModuleNotFoundError: No module named 'ftfy'
```

Doing a `pip install ftfy` worked but then got `No module named 'regex'` (after `pip install regex` it ran for a bit then errored with `No module named 'tensorflow'` and that's as far as I've gotten).

**Comment by yeldarby** [comment]
Fixed by https://github.com/roboflow-ai/zero-shot-object-tracking/commit/8a03377b68a7e15b49faacb37f6c3d56a67f53c7
