### ISSUE TITLE
cv2.error Assertion failed !image.empty() in function 'imencode'

### ISSUE THREAD

**Issue by yeldarby** [roboflow-ai/zero-shot-object-tracking#2]
After it does all the detections I get an error on cv2.imencode:
```
video 1/1 (42/83) /Users/yeldarb/Downloads/cards-720.mov: Traceback (most recent call last):
  File "/Users/yeldarb/Code/zero-shot-object-tracking/clip_object_tracker.py", line 263, in <module>
    detect()
  File "/Users/yeldarb/Code/zero-shot-object-tracking/clip_object_tracker.py", line 110, in detect
    pred, classes = predict_image(vid_cap, opt.api_key, opt.url, frame_count)
  File "/Users/yeldarb/Code/zero-shot-object-tracking/utils/roboflow.py", line 11, in predict_image
    retval, buffer = cv2.imencode('.jpg', image)
cv2.error: OpenCV(4.5.3) /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-req-build-vy_omupv/opencv/modules/imgcodecs/src/loadsave.cpp:978: error: (-215:Assertion failed) !image.empty() in function 'imencode'
```

**Comment by yeldarby** [comment]
Fixed by https://github.com/roboflow-ai/zero-shot-object-tracking/commit/c0c46f0df7b352735c09cacd2fa4b59f799b5dfa
